import type {Metadata} from "next";
import "./globals.css";
import '@/assets/style/common.scss'
import Header from '@/app/layout/Header'
import React from "react";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header/>
                {children}
            </body>
        </html>
    );
}
